// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

public interface MitmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string method = 2;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  java.util.List<com.deep007.mitmproxyjava.MitmHeader> 
      getHeadersList();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  com.deep007.mitmproxyjava.MitmHeader getHeaders(int index);
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  int getHeadersCount();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  java.util.List<? extends com.deep007.mitmproxyjava.MitmHeaderOrBuilder> 
      getHeadersOrBuilderList();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  com.deep007.mitmproxyjava.MitmHeaderOrBuilder getHeadersOrBuilder(
      int index);

  /**
   * <code>bytes content = 4;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>string mitmproxyId = 5;</code>
   */
  java.lang.String getMitmproxyId();
  /**
   * <code>string mitmproxyId = 5;</code>
   */
  com.google.protobuf.ByteString
      getMitmproxyIdBytes();
}
