// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

/**
 * Protobuf type {@code mitm.MitmproxyStopRequest}
 */
public  final class MitmproxyStopRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmproxyStopRequest)
    MitmproxyStopRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmproxyStopRequest.newBuilder() to construct.
  private MitmproxyStopRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmproxyStopRequest() {
    mitmproxyId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmproxyStopRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mitmproxyId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStopRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStopRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.mitmproxyjava.MitmproxyStopRequest.class, com.deep007.mitmproxyjava.MitmproxyStopRequest.Builder.class);
  }

  public static final int MITMPROXYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object mitmproxyId_;
  /**
   * <code>string mitmproxyId = 1;</code>
   */
  public java.lang.String getMitmproxyId() {
    java.lang.Object ref = mitmproxyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mitmproxyId_ = s;
      return s;
    }
  }
  /**
   * <code>string mitmproxyId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMitmproxyIdBytes() {
    java.lang.Object ref = mitmproxyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mitmproxyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMitmproxyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mitmproxyId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMitmproxyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mitmproxyId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.mitmproxyjava.MitmproxyStopRequest)) {
      return super.equals(obj);
    }
    com.deep007.mitmproxyjava.MitmproxyStopRequest other = (com.deep007.mitmproxyjava.MitmproxyStopRequest) obj;

    boolean result = true;
    result = result && getMitmproxyId()
        .equals(other.getMitmproxyId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MITMPROXYID_FIELD_NUMBER;
    hash = (53 * hash) + getMitmproxyId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStopRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.mitmproxyjava.MitmproxyStopRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmproxyStopRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmproxyStopRequest)
      com.deep007.mitmproxyjava.MitmproxyStopRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStopRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStopRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.mitmproxyjava.MitmproxyStopRequest.class, com.deep007.mitmproxyjava.MitmproxyStopRequest.Builder.class);
    }

    // Construct using com.deep007.mitmproxyjava.MitmproxyStopRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mitmproxyId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStopRequest_descriptor;
    }

    public com.deep007.mitmproxyjava.MitmproxyStopRequest getDefaultInstanceForType() {
      return com.deep007.mitmproxyjava.MitmproxyStopRequest.getDefaultInstance();
    }

    public com.deep007.mitmproxyjava.MitmproxyStopRequest build() {
      com.deep007.mitmproxyjava.MitmproxyStopRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.mitmproxyjava.MitmproxyStopRequest buildPartial() {
      com.deep007.mitmproxyjava.MitmproxyStopRequest result = new com.deep007.mitmproxyjava.MitmproxyStopRequest(this);
      result.mitmproxyId_ = mitmproxyId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.mitmproxyjava.MitmproxyStopRequest) {
        return mergeFrom((com.deep007.mitmproxyjava.MitmproxyStopRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.mitmproxyjava.MitmproxyStopRequest other) {
      if (other == com.deep007.mitmproxyjava.MitmproxyStopRequest.getDefaultInstance()) return this;
      if (!other.getMitmproxyId().isEmpty()) {
        mitmproxyId_ = other.mitmproxyId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.mitmproxyjava.MitmproxyStopRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.mitmproxyjava.MitmproxyStopRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mitmproxyId_ = "";
    /**
     * <code>string mitmproxyId = 1;</code>
     */
    public java.lang.String getMitmproxyId() {
      java.lang.Object ref = mitmproxyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mitmproxyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mitmproxyId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMitmproxyIdBytes() {
      java.lang.Object ref = mitmproxyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mitmproxyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mitmproxyId = 1;</code>
     */
    public Builder setMitmproxyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mitmproxyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mitmproxyId = 1;</code>
     */
    public Builder clearMitmproxyId() {
      
      mitmproxyId_ = getDefaultInstance().getMitmproxyId();
      onChanged();
      return this;
    }
    /**
     * <code>string mitmproxyId = 1;</code>
     */
    public Builder setMitmproxyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mitmproxyId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmproxyStopRequest)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmproxyStopRequest)
  private static final com.deep007.mitmproxyjava.MitmproxyStopRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.mitmproxyjava.MitmproxyStopRequest();
  }

  public static com.deep007.mitmproxyjava.MitmproxyStopRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmproxyStopRequest>
      PARSER = new com.google.protobuf.AbstractParser<MitmproxyStopRequest>() {
    public MitmproxyStopRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmproxyStopRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmproxyStopRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmproxyStopRequest> getParserForType() {
    return PARSER;
  }

  public com.deep007.mitmproxyjava.MitmproxyStopRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

