// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

public interface MitmproxyStartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmproxyStartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bind = 1;</code>
   */
  java.lang.String getBind();
  /**
   * <code>string bind = 1;</code>
   */
  com.google.protobuf.ByteString
      getBindBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string callbackServerAddr = 3;</code>
   */
  java.lang.String getCallbackServerAddr();
  /**
   * <code>string callbackServerAddr = 3;</code>
   */
  com.google.protobuf.ByteString
      getCallbackServerAddrBytes();

  /**
   * <code>int32 callbackServerPort = 4;</code>
   */
  int getCallbackServerPort();
}
