// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

public final class MitmProxyHubClientServerProto {
  private MitmProxyHubClientServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_VoidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_VoidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmproxyStartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmproxyStartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmproxyStartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmproxyStartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmproxyStopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmproxyStopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025mitm_hub_client.proto\022\004mitm\"\016\n\014VoidRes" +
      "ponse\"k\n\025MitmproxyStartRequest\022\014\n\004bind\030\001" +
      " \001(\t\022\014\n\004port\030\002 \001(\005\022\032\n\022callbackServerAddr" +
      "\030\003 \001(\t\022\032\n\022callbackServerPort\030\004 \001(\005\"-\n\026Mi" +
      "tmproxyStartResponse\022\023\n\013mitmproxyId\030\001 \001(" +
      "\t\"+\n\024MitmproxyStopRequest\022\023\n\013mitmproxyId" +
      "\030\001 \001(\t\")\n\nMitmHeader\022\014\n\004name\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t\"s\n\013MitmRequest\022\013\n\003url\030\001 \001(\t\022\016\n" +
      "\006method\030\002 \001(\t\022!\n\007headers\030\003 \003(\0132\020.mitm.Mi" +
      "tmHeader\022\017\n\007content\030\004 \001(\014\022\023\n\013mitmproxyId" +
      "\030\005 \001(\t\"\217\001\n\014MitmResponse\022\"\n\007request\030\001 \001(\013" +
      "2\021.mitm.MitmRequest\022!\n\007headers\030\002 \003(\0132\020.m" +
      "itm.MitmHeader\022\017\n\007content\030\003 \001(\014\022\022\n\nstatu" +
      "sCode\030\004 \001(\005\022\023\n\013mitmproxyId\030\005 \001(\t2\224\001\n\022Mit" +
      "mProxyHubServer\022D\n\005start\022\033.mitm.Mitmprox" +
      "yStartRequest\032\034.mitm.MitmproxyStartRespo" +
      "nse\"\000\0228\n\004stop\022\032.mitm.MitmproxyStopReques" +
      "t\032\022.mitm.VoidResponse\"\0002\217\001\n\030MitmProxyHub" +
      "ClientServer\0227\n\ronMitmRequest\022\021.mitm.Mit" +
      "mRequest\032\021.mitm.MitmRequest\"\000\022:\n\016onMitmR" +
      "esponse\022\022.mitm.MitmResponse\032\022.mitm.MitmR" +
      "esponse\"\000B<\n\031com.deep007.mitmproxyjavaB\035" +
      "MitmProxyHubClientServerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mitm_VoidResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mitm_VoidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_VoidResponse_descriptor,
        new java.lang.String[] { });
    internal_static_mitm_MitmproxyStartRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mitm_MitmproxyStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmproxyStartRequest_descriptor,
        new java.lang.String[] { "Bind", "Port", "CallbackServerAddr", "CallbackServerPort", });
    internal_static_mitm_MitmproxyStartResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mitm_MitmproxyStartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmproxyStartResponse_descriptor,
        new java.lang.String[] { "MitmproxyId", });
    internal_static_mitm_MitmproxyStopRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mitm_MitmproxyStopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmproxyStopRequest_descriptor,
        new java.lang.String[] { "MitmproxyId", });
    internal_static_mitm_MitmHeader_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mitm_MitmHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmHeader_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_mitm_MitmRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mitm_MitmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmRequest_descriptor,
        new java.lang.String[] { "Url", "Method", "Headers", "Content", "MitmproxyId", });
    internal_static_mitm_MitmResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mitm_MitmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmResponse_descriptor,
        new java.lang.String[] { "Request", "Headers", "Content", "StatusCode", "MitmproxyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
