// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

/**
 * Protobuf type {@code mitm.MitmproxyStartRequest}
 */
public  final class MitmproxyStartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmproxyStartRequest)
    MitmproxyStartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmproxyStartRequest.newBuilder() to construct.
  private MitmproxyStartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmproxyStartRequest() {
    bind_ = "";
    port_ = 0;
    callbackServerAddr_ = "";
    callbackServerPort_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmproxyStartRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bind_ = s;
            break;
          }
          case 16: {

            port_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            callbackServerAddr_ = s;
            break;
          }
          case 32: {

            callbackServerPort_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStartRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.mitmproxyjava.MitmproxyStartRequest.class, com.deep007.mitmproxyjava.MitmproxyStartRequest.Builder.class);
  }

  public static final int BIND_FIELD_NUMBER = 1;
  private volatile java.lang.Object bind_;
  /**
   * <code>string bind = 1;</code>
   */
  public java.lang.String getBind() {
    java.lang.Object ref = bind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bind_ = s;
      return s;
    }
  }
  /**
   * <code>string bind = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBindBytes() {
    java.lang.Object ref = bind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private int port_;
  /**
   * <code>int32 port = 2;</code>
   */
  public int getPort() {
    return port_;
  }

  public static final int CALLBACKSERVERADDR_FIELD_NUMBER = 3;
  private volatile java.lang.Object callbackServerAddr_;
  /**
   * <code>string callbackServerAddr = 3;</code>
   */
  public java.lang.String getCallbackServerAddr() {
    java.lang.Object ref = callbackServerAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callbackServerAddr_ = s;
      return s;
    }
  }
  /**
   * <code>string callbackServerAddr = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCallbackServerAddrBytes() {
    java.lang.Object ref = callbackServerAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callbackServerAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLBACKSERVERPORT_FIELD_NUMBER = 4;
  private int callbackServerPort_;
  /**
   * <code>int32 callbackServerPort = 4;</code>
   */
  public int getCallbackServerPort() {
    return callbackServerPort_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBindBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bind_);
    }
    if (port_ != 0) {
      output.writeInt32(2, port_);
    }
    if (!getCallbackServerAddrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, callbackServerAddr_);
    }
    if (callbackServerPort_ != 0) {
      output.writeInt32(4, callbackServerPort_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBindBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bind_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, port_);
    }
    if (!getCallbackServerAddrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, callbackServerAddr_);
    }
    if (callbackServerPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, callbackServerPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.mitmproxyjava.MitmproxyStartRequest)) {
      return super.equals(obj);
    }
    com.deep007.mitmproxyjava.MitmproxyStartRequest other = (com.deep007.mitmproxyjava.MitmproxyStartRequest) obj;

    boolean result = true;
    result = result && getBind()
        .equals(other.getBind());
    result = result && (getPort()
        == other.getPort());
    result = result && getCallbackServerAddr()
        .equals(other.getCallbackServerAddr());
    result = result && (getCallbackServerPort()
        == other.getCallbackServerPort());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BIND_FIELD_NUMBER;
    hash = (53 * hash) + getBind().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + CALLBACKSERVERADDR_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackServerAddr().hashCode();
    hash = (37 * hash) + CALLBACKSERVERPORT_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackServerPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmproxyStartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.mitmproxyjava.MitmproxyStartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmproxyStartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmproxyStartRequest)
      com.deep007.mitmproxyjava.MitmproxyStartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStartRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.mitmproxyjava.MitmproxyStartRequest.class, com.deep007.mitmproxyjava.MitmproxyStartRequest.Builder.class);
    }

    // Construct using com.deep007.mitmproxyjava.MitmproxyStartRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      bind_ = "";

      port_ = 0;

      callbackServerAddr_ = "";

      callbackServerPort_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmproxyStartRequest_descriptor;
    }

    public com.deep007.mitmproxyjava.MitmproxyStartRequest getDefaultInstanceForType() {
      return com.deep007.mitmproxyjava.MitmproxyStartRequest.getDefaultInstance();
    }

    public com.deep007.mitmproxyjava.MitmproxyStartRequest build() {
      com.deep007.mitmproxyjava.MitmproxyStartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.mitmproxyjava.MitmproxyStartRequest buildPartial() {
      com.deep007.mitmproxyjava.MitmproxyStartRequest result = new com.deep007.mitmproxyjava.MitmproxyStartRequest(this);
      result.bind_ = bind_;
      result.port_ = port_;
      result.callbackServerAddr_ = callbackServerAddr_;
      result.callbackServerPort_ = callbackServerPort_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.mitmproxyjava.MitmproxyStartRequest) {
        return mergeFrom((com.deep007.mitmproxyjava.MitmproxyStartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.mitmproxyjava.MitmproxyStartRequest other) {
      if (other == com.deep007.mitmproxyjava.MitmproxyStartRequest.getDefaultInstance()) return this;
      if (!other.getBind().isEmpty()) {
        bind_ = other.bind_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (!other.getCallbackServerAddr().isEmpty()) {
        callbackServerAddr_ = other.callbackServerAddr_;
        onChanged();
      }
      if (other.getCallbackServerPort() != 0) {
        setCallbackServerPort(other.getCallbackServerPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.mitmproxyjava.MitmproxyStartRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.mitmproxyjava.MitmproxyStartRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bind_ = "";
    /**
     * <code>string bind = 1;</code>
     */
    public java.lang.String getBind() {
      java.lang.Object ref = bind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bind = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBindBytes() {
      java.lang.Object ref = bind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bind = 1;</code>
     */
    public Builder setBind(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bind = 1;</code>
     */
    public Builder clearBind() {
      
      bind_ = getDefaultInstance().getBind();
      onChanged();
      return this;
    }
    /**
     * <code>string bind = 1;</code>
     */
    public Builder setBindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bind_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object callbackServerAddr_ = "";
    /**
     * <code>string callbackServerAddr = 3;</code>
     */
    public java.lang.String getCallbackServerAddr() {
      java.lang.Object ref = callbackServerAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callbackServerAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string callbackServerAddr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCallbackServerAddrBytes() {
      java.lang.Object ref = callbackServerAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callbackServerAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string callbackServerAddr = 3;</code>
     */
    public Builder setCallbackServerAddr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callbackServerAddr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string callbackServerAddr = 3;</code>
     */
    public Builder clearCallbackServerAddr() {
      
      callbackServerAddr_ = getDefaultInstance().getCallbackServerAddr();
      onChanged();
      return this;
    }
    /**
     * <code>string callbackServerAddr = 3;</code>
     */
    public Builder setCallbackServerAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callbackServerAddr_ = value;
      onChanged();
      return this;
    }

    private int callbackServerPort_ ;
    /**
     * <code>int32 callbackServerPort = 4;</code>
     */
    public int getCallbackServerPort() {
      return callbackServerPort_;
    }
    /**
     * <code>int32 callbackServerPort = 4;</code>
     */
    public Builder setCallbackServerPort(int value) {
      
      callbackServerPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 callbackServerPort = 4;</code>
     */
    public Builder clearCallbackServerPort() {
      
      callbackServerPort_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmproxyStartRequest)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmproxyStartRequest)
  private static final com.deep007.mitmproxyjava.MitmproxyStartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.mitmproxyjava.MitmproxyStartRequest();
  }

  public static com.deep007.mitmproxyjava.MitmproxyStartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmproxyStartRequest>
      PARSER = new com.google.protobuf.AbstractParser<MitmproxyStartRequest>() {
    public MitmproxyStartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmproxyStartRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmproxyStartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmproxyStartRequest> getParserForType() {
    return PARSER;
  }

  public com.deep007.mitmproxyjava.MitmproxyStartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

