// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

public interface MitmproxyStartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmproxyStartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mitmproxyId = 1;</code>
   */
  java.lang.String getMitmproxyId();
  /**
   * <code>string mitmproxyId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMitmproxyIdBytes();
}
