// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

/**
 * Protobuf type {@code mitm.MitmResponse}
 */
public  final class MitmResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmResponse)
    MitmResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmResponse.newBuilder() to construct.
  private MitmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmResponse() {
    headers_ = java.util.Collections.emptyList();
    content_ = com.google.protobuf.ByteString.EMPTY;
    statusCode_ = 0;
    mitmproxyId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.deep007.mitmproxyjava.MitmRequest.Builder subBuilder = null;
            if (request_ != null) {
              subBuilder = request_.toBuilder();
            }
            request_ = input.readMessage(com.deep007.mitmproxyjava.MitmRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(request_);
              request_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              headers_ = new java.util.ArrayList<com.deep007.mitmproxyjava.MitmHeader>();
              mutable_bitField0_ |= 0x00000002;
            }
            headers_.add(
                input.readMessage(com.deep007.mitmproxyjava.MitmHeader.parser(), extensionRegistry));
            break;
          }
          case 26: {

            content_ = input.readBytes();
            break;
          }
          case 32: {

            statusCode_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            mitmproxyId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        headers_ = java.util.Collections.unmodifiableList(headers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.mitmproxyjava.MitmResponse.class, com.deep007.mitmproxyjava.MitmResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_FIELD_NUMBER = 1;
  private com.deep007.mitmproxyjava.MitmRequest request_;
  /**
   * <code>.mitm.MitmRequest request = 1;</code>
   */
  public boolean hasRequest() {
    return request_ != null;
  }
  /**
   * <code>.mitm.MitmRequest request = 1;</code>
   */
  public com.deep007.mitmproxyjava.MitmRequest getRequest() {
    return request_ == null ? com.deep007.mitmproxyjava.MitmRequest.getDefaultInstance() : request_;
  }
  /**
   * <code>.mitm.MitmRequest request = 1;</code>
   */
  public com.deep007.mitmproxyjava.MitmRequestOrBuilder getRequestOrBuilder() {
    return getRequest();
  }

  public static final int HEADERS_FIELD_NUMBER = 2;
  private java.util.List<com.deep007.mitmproxyjava.MitmHeader> headers_;
  /**
   * <code>repeated .mitm.MitmHeader headers = 2;</code>
   */
  public java.util.List<com.deep007.mitmproxyjava.MitmHeader> getHeadersList() {
    return headers_;
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 2;</code>
   */
  public java.util.List<? extends com.deep007.mitmproxyjava.MitmHeaderOrBuilder> 
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 2;</code>
   */
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 2;</code>
   */
  public com.deep007.mitmproxyjava.MitmHeader getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 2;</code>
   */
  public com.deep007.mitmproxyjava.MitmHeaderOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString content_;
  /**
   * <code>bytes content = 3;</code>
   */
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  public static final int STATUSCODE_FIELD_NUMBER = 4;
  private int statusCode_;
  /**
   * <code>int32 statusCode = 4;</code>
   */
  public int getStatusCode() {
    return statusCode_;
  }

  public static final int MITMPROXYID_FIELD_NUMBER = 5;
  private volatile java.lang.Object mitmproxyId_;
  /**
   * <code>string mitmproxyId = 5;</code>
   */
  public java.lang.String getMitmproxyId() {
    java.lang.Object ref = mitmproxyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mitmproxyId_ = s;
      return s;
    }
  }
  /**
   * <code>string mitmproxyId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getMitmproxyIdBytes() {
    java.lang.Object ref = mitmproxyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mitmproxyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (request_ != null) {
      output.writeMessage(1, getRequest());
    }
    for (int i = 0; i < headers_.size(); i++) {
      output.writeMessage(2, headers_.get(i));
    }
    if (!content_.isEmpty()) {
      output.writeBytes(3, content_);
    }
    if (statusCode_ != 0) {
      output.writeInt32(4, statusCode_);
    }
    if (!getMitmproxyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mitmproxyId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (request_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequest());
    }
    for (int i = 0; i < headers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, headers_.get(i));
    }
    if (!content_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, content_);
    }
    if (statusCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, statusCode_);
    }
    if (!getMitmproxyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mitmproxyId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.mitmproxyjava.MitmResponse)) {
      return super.equals(obj);
    }
    com.deep007.mitmproxyjava.MitmResponse other = (com.deep007.mitmproxyjava.MitmResponse) obj;

    boolean result = true;
    result = result && (hasRequest() == other.hasRequest());
    if (hasRequest()) {
      result = result && getRequest()
          .equals(other.getRequest());
    }
    result = result && getHeadersList()
        .equals(other.getHeadersList());
    result = result && getContent()
        .equals(other.getContent());
    result = result && (getStatusCode()
        == other.getStatusCode());
    result = result && getMitmproxyId()
        .equals(other.getMitmproxyId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequest()) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
    }
    if (getHeadersCount() > 0) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeadersList().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatusCode();
    hash = (37 * hash) + MITMPROXYID_FIELD_NUMBER;
    hash = (53 * hash) + getMitmproxyId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.mitmproxyjava.MitmResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.mitmproxyjava.MitmResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmResponse)
      com.deep007.mitmproxyjava.MitmResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.mitmproxyjava.MitmResponse.class, com.deep007.mitmproxyjava.MitmResponse.Builder.class);
    }

    // Construct using com.deep007.mitmproxyjava.MitmResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeadersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (requestBuilder_ == null) {
        request_ = null;
      } else {
        request_ = null;
        requestBuilder_ = null;
      }
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        headersBuilder_.clear();
      }
      content_ = com.google.protobuf.ByteString.EMPTY;

      statusCode_ = 0;

      mitmproxyId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.mitmproxyjava.MitmProxyHubClientServerProto.internal_static_mitm_MitmResponse_descriptor;
    }

    public com.deep007.mitmproxyjava.MitmResponse getDefaultInstanceForType() {
      return com.deep007.mitmproxyjava.MitmResponse.getDefaultInstance();
    }

    public com.deep007.mitmproxyjava.MitmResponse build() {
      com.deep007.mitmproxyjava.MitmResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.mitmproxyjava.MitmResponse buildPartial() {
      com.deep007.mitmproxyjava.MitmResponse result = new com.deep007.mitmproxyjava.MitmResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (requestBuilder_ == null) {
        result.request_ = request_;
      } else {
        result.request_ = requestBuilder_.build();
      }
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.headers_ = headers_;
      } else {
        result.headers_ = headersBuilder_.build();
      }
      result.content_ = content_;
      result.statusCode_ = statusCode_;
      result.mitmproxyId_ = mitmproxyId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.mitmproxyjava.MitmResponse) {
        return mergeFrom((com.deep007.mitmproxyjava.MitmResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.mitmproxyjava.MitmResponse other) {
      if (other == com.deep007.mitmproxyjava.MitmResponse.getDefaultInstance()) return this;
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (headersBuilder_ == null) {
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
      } else {
        if (!other.headers_.isEmpty()) {
          if (headersBuilder_.isEmpty()) {
            headersBuilder_.dispose();
            headersBuilder_ = null;
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            headersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeadersFieldBuilder() : null;
          } else {
            headersBuilder_.addAllMessages(other.headers_);
          }
        }
      }
      if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
        setContent(other.getContent());
      }
      if (other.getStatusCode() != 0) {
        setStatusCode(other.getStatusCode());
      }
      if (!other.getMitmproxyId().isEmpty()) {
        mitmproxyId_ = other.mitmproxyId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.mitmproxyjava.MitmResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.mitmproxyjava.MitmResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.deep007.mitmproxyjava.MitmRequest request_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.deep007.mitmproxyjava.MitmRequest, com.deep007.mitmproxyjava.MitmRequest.Builder, com.deep007.mitmproxyjava.MitmRequestOrBuilder> requestBuilder_;
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return requestBuilder_ != null || request_ != null;
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public com.deep007.mitmproxyjava.MitmRequest getRequest() {
      if (requestBuilder_ == null) {
        return request_ == null ? com.deep007.mitmproxyjava.MitmRequest.getDefaultInstance() : request_;
      } else {
        return requestBuilder_.getMessage();
      }
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public Builder setRequest(com.deep007.mitmproxyjava.MitmRequest value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public Builder setRequest(
        com.deep007.mitmproxyjava.MitmRequest.Builder builderForValue) {
      if (requestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public Builder mergeRequest(com.deep007.mitmproxyjava.MitmRequest value) {
      if (requestBuilder_ == null) {
        if (request_ != null) {
          request_ =
            com.deep007.mitmproxyjava.MitmRequest.newBuilder(request_).mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        requestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        request_ = null;
        onChanged();
      } else {
        request_ = null;
        requestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public com.deep007.mitmproxyjava.MitmRequest.Builder getRequestBuilder() {
      
      onChanged();
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    public com.deep007.mitmproxyjava.MitmRequestOrBuilder getRequestOrBuilder() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        return request_ == null ?
            com.deep007.mitmproxyjava.MitmRequest.getDefaultInstance() : request_;
      }
    }
    /**
     * <code>.mitm.MitmRequest request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.deep007.mitmproxyjava.MitmRequest, com.deep007.mitmproxyjava.MitmRequest.Builder, com.deep007.mitmproxyjava.MitmRequestOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.deep007.mitmproxyjava.MitmRequest, com.deep007.mitmproxyjava.MitmRequest.Builder, com.deep007.mitmproxyjava.MitmRequestOrBuilder>(
                getRequest(),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }

    private java.util.List<com.deep007.mitmproxyjava.MitmHeader> headers_ =
      java.util.Collections.emptyList();
    private void ensureHeadersIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        headers_ = new java.util.ArrayList<com.deep007.mitmproxyjava.MitmHeader>(headers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.deep007.mitmproxyjava.MitmHeader, com.deep007.mitmproxyjava.MitmHeader.Builder, com.deep007.mitmproxyjava.MitmHeaderOrBuilder> headersBuilder_;

    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public java.util.List<com.deep007.mitmproxyjava.MitmHeader> getHeadersList() {
      if (headersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(headers_);
      } else {
        return headersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public int getHeadersCount() {
      if (headersBuilder_ == null) {
        return headers_.size();
      } else {
        return headersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public com.deep007.mitmproxyjava.MitmHeader getHeaders(int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);
      } else {
        return headersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder setHeaders(
        int index, com.deep007.mitmproxyjava.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
      } else {
        headersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder setHeaders(
        int index, com.deep007.mitmproxyjava.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.set(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder addHeaders(com.deep007.mitmproxyjava.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
      } else {
        headersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder addHeaders(
        int index, com.deep007.mitmproxyjava.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(index, value);
        onChanged();
      } else {
        headersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder addHeaders(
        com.deep007.mitmproxyjava.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder addHeaders(
        int index, com.deep007.mitmproxyjava.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder addAllHeaders(
        java.lang.Iterable<? extends com.deep007.mitmproxyjava.MitmHeader> values) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
      } else {
        headersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder clearHeaders() {
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        headersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public Builder removeHeaders(int index) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.remove(index);
        onChanged();
      } else {
        headersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public com.deep007.mitmproxyjava.MitmHeader.Builder getHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public com.deep007.mitmproxyjava.MitmHeaderOrBuilder getHeadersOrBuilder(
        int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);  } else {
        return headersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public java.util.List<? extends com.deep007.mitmproxyjava.MitmHeaderOrBuilder> 
         getHeadersOrBuilderList() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(headers_);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public com.deep007.mitmproxyjava.MitmHeader.Builder addHeadersBuilder() {
      return getHeadersFieldBuilder().addBuilder(
          com.deep007.mitmproxyjava.MitmHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public com.deep007.mitmproxyjava.MitmHeader.Builder addHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().addBuilder(
          index, com.deep007.mitmproxyjava.MitmHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 2;</code>
     */
    public java.util.List<com.deep007.mitmproxyjava.MitmHeader.Builder> 
         getHeadersBuilderList() {
      return getHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.deep007.mitmproxyjava.MitmHeader, com.deep007.mitmproxyjava.MitmHeader.Builder, com.deep007.mitmproxyjava.MitmHeaderOrBuilder> 
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.deep007.mitmproxyjava.MitmHeader, com.deep007.mitmproxyjava.MitmHeader.Builder, com.deep007.mitmproxyjava.MitmHeaderOrBuilder>(
                headers_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <code>bytes content = 3;</code>
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes content = 3;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }

    private int statusCode_ ;
    /**
     * <code>int32 statusCode = 4;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <code>int32 statusCode = 4;</code>
     */
    public Builder setStatusCode(int value) {
      
      statusCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 statusCode = 4;</code>
     */
    public Builder clearStatusCode() {
      
      statusCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mitmproxyId_ = "";
    /**
     * <code>string mitmproxyId = 5;</code>
     */
    public java.lang.String getMitmproxyId() {
      java.lang.Object ref = mitmproxyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mitmproxyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mitmproxyId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMitmproxyIdBytes() {
      java.lang.Object ref = mitmproxyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mitmproxyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mitmproxyId = 5;</code>
     */
    public Builder setMitmproxyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mitmproxyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mitmproxyId = 5;</code>
     */
    public Builder clearMitmproxyId() {
      
      mitmproxyId_ = getDefaultInstance().getMitmproxyId();
      onChanged();
      return this;
    }
    /**
     * <code>string mitmproxyId = 5;</code>
     */
    public Builder setMitmproxyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mitmproxyId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmResponse)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmResponse)
  private static final com.deep007.mitmproxyjava.MitmResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.mitmproxyjava.MitmResponse();
  }

  public static com.deep007.mitmproxyjava.MitmResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmResponse>
      PARSER = new com.google.protobuf.AbstractParser<MitmResponse>() {
    public MitmResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmResponse> getParserForType() {
    return PARSER;
  }

  public com.deep007.mitmproxyjava.MitmResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

