// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_hub_client.proto

package com.deep007.mitmproxyjava;

public interface VoidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.VoidResponse)
    com.google.protobuf.MessageOrBuilder {
}
