# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mitm_flow_pb2 as mitm__flow__pb2


class MitmFlowMonitorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.onMitmRequest = channel.unary_unary(
                '/mitm.MitmFlowMonitor/onMitmRequest',
                request_serializer=mitm__flow__pb2.MitmRequest.SerializeToString,
                response_deserializer=mitm__flow__pb2.MitmRequest.FromString,
                )
        self.onMitmResponse = channel.unary_unary(
                '/mitm.MitmFlowMonitor/onMitmResponse',
                request_serializer=mitm__flow__pb2.MitmResponse.SerializeToString,
                response_deserializer=mitm__flow__pb2.MitmResponse.FromString,
                )


class MitmFlowMonitorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def onMitmRequest(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def onMitmResponse(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MitmFlowMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'onMitmRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.onMitmRequest,
                    request_deserializer=mitm__flow__pb2.MitmRequest.FromString,
                    response_serializer=mitm__flow__pb2.MitmRequest.SerializeToString,
            ),
            'onMitmResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.onMitmResponse,
                    request_deserializer=mitm__flow__pb2.MitmResponse.FromString,
                    response_serializer=mitm__flow__pb2.MitmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mitm.MitmFlowMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MitmFlowMonitor(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def onMitmRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mitm.MitmFlowMonitor/onMitmRequest',
            mitm__flow__pb2.MitmRequest.SerializeToString,
            mitm__flow__pb2.MitmRequest.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def onMitmResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mitm.MitmFlowMonitor/onMitmResponse',
            mitm__flow__pb2.MitmResponse.SerializeToString,
            mitm__flow__pb2.MitmResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
