// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

/**
 * Protobuf type {@code mitm.MitmBinding}
 */
public  final class MitmBinding extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmBinding)
    MitmBindingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmBinding.newBuilder() to construct.
  private MitmBinding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmBinding() {
    mitmserverId_ = "";
    browserId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmBinding(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mitmserverId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            browserId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmBinding_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmBinding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.goniub.selenium.mitm.monitor.MitmBinding.class, com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder.class);
  }

  public static final int MITMSERVERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object mitmserverId_;
  /**
   * <code>string mitmserverId = 1;</code>
   */
  public java.lang.String getMitmserverId() {
    java.lang.Object ref = mitmserverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mitmserverId_ = s;
      return s;
    }
  }
  /**
   * <code>string mitmserverId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMitmserverIdBytes() {
    java.lang.Object ref = mitmserverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mitmserverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROWSERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object browserId_;
  /**
   * <code>string browserId = 2;</code>
   */
  public java.lang.String getBrowserId() {
    java.lang.Object ref = browserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      browserId_ = s;
      return s;
    }
  }
  /**
   * <code>string browserId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBrowserIdBytes() {
    java.lang.Object ref = browserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      browserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMitmserverIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mitmserverId_);
    }
    if (!getBrowserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, browserId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMitmserverIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mitmserverId_);
    }
    if (!getBrowserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, browserId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.goniub.selenium.mitm.monitor.MitmBinding)) {
      return super.equals(obj);
    }
    com.deep007.goniub.selenium.mitm.monitor.MitmBinding other = (com.deep007.goniub.selenium.mitm.monitor.MitmBinding) obj;

    boolean result = true;
    result = result && getMitmserverId()
        .equals(other.getMitmserverId());
    result = result && getBrowserId()
        .equals(other.getBrowserId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MITMSERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getMitmserverId().hashCode();
    hash = (37 * hash) + BROWSERID_FIELD_NUMBER;
    hash = (53 * hash) + getBrowserId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.goniub.selenium.mitm.monitor.MitmBinding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmBinding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmBinding)
      com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmBinding_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmBinding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.goniub.selenium.mitm.monitor.MitmBinding.class, com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder.class);
    }

    // Construct using com.deep007.goniub.selenium.mitm.monitor.MitmBinding.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mitmserverId_ = "";

      browserId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmBinding_descriptor;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmBinding getDefaultInstanceForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmBinding.getDefaultInstance();
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmBinding build() {
      com.deep007.goniub.selenium.mitm.monitor.MitmBinding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmBinding buildPartial() {
      com.deep007.goniub.selenium.mitm.monitor.MitmBinding result = new com.deep007.goniub.selenium.mitm.monitor.MitmBinding(this);
      result.mitmserverId_ = mitmserverId_;
      result.browserId_ = browserId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.goniub.selenium.mitm.monitor.MitmBinding) {
        return mergeFrom((com.deep007.goniub.selenium.mitm.monitor.MitmBinding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.goniub.selenium.mitm.monitor.MitmBinding other) {
      if (other == com.deep007.goniub.selenium.mitm.monitor.MitmBinding.getDefaultInstance()) return this;
      if (!other.getMitmserverId().isEmpty()) {
        mitmserverId_ = other.mitmserverId_;
        onChanged();
      }
      if (!other.getBrowserId().isEmpty()) {
        browserId_ = other.browserId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.goniub.selenium.mitm.monitor.MitmBinding parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.goniub.selenium.mitm.monitor.MitmBinding) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mitmserverId_ = "";
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public java.lang.String getMitmserverId() {
      java.lang.Object ref = mitmserverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mitmserverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMitmserverIdBytes() {
      java.lang.Object ref = mitmserverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mitmserverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder setMitmserverId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mitmserverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder clearMitmserverId() {
      
      mitmserverId_ = getDefaultInstance().getMitmserverId();
      onChanged();
      return this;
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder setMitmserverIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mitmserverId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object browserId_ = "";
    /**
     * <code>string browserId = 2;</code>
     */
    public java.lang.String getBrowserId() {
      java.lang.Object ref = browserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        browserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string browserId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrowserIdBytes() {
      java.lang.Object ref = browserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        browserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string browserId = 2;</code>
     */
    public Builder setBrowserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      browserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string browserId = 2;</code>
     */
    public Builder clearBrowserId() {
      
      browserId_ = getDefaultInstance().getBrowserId();
      onChanged();
      return this;
    }
    /**
     * <code>string browserId = 2;</code>
     */
    public Builder setBrowserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      browserId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmBinding)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmBinding)
  private static final com.deep007.goniub.selenium.mitm.monitor.MitmBinding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.goniub.selenium.mitm.monitor.MitmBinding();
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmBinding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmBinding>
      PARSER = new com.google.protobuf.AbstractParser<MitmBinding>() {
    public MitmBinding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmBinding(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmBinding> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmBinding> getParserForType() {
    return PARSER;
  }

  public com.deep007.goniub.selenium.mitm.monitor.MitmBinding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

