// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

public final class MitmFlowMonitorProto {
  private MitmFlowMonitorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mitm_MitmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mitm_MitmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mitm_flow.proto\022\004mitm\"A\n\013MitmRequest\022\024" +
      "\n\014mitmserverId\030\001 \001(\t\022\017\n\007cloudId\030\002 \001(\t\022\013\n" +
      "\003url\030\003 \001(\t\"S\n\014MitmResponse\022\024\n\014mitmserver" +
      "Id\030\001 \001(\t\022\017\n\007cloudId\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\017" +
      "\n\007content\030\004 \001(\0142\206\001\n\017MitmFlowMonitor\0227\n\ro" +
      "nMitmRequest\022\021.mitm.MitmRequest\032\021.mitm.M" +
      "itmRequest\"\000\022:\n\016onMitmResponse\022\022.mitm.Mi" +
      "tmResponse\032\022.mitm.MitmResponse\"\000BB\n(com." +
      "deep007.goniub.selenium.mitm.monitorB\024Mi" +
      "tmFlowMonitorProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mitm_MitmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mitm_MitmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmRequest_descriptor,
        new java.lang.String[] { "MitmserverId", "CloudId", "Url", });
    internal_static_mitm_MitmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mitm_MitmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mitm_MitmResponse_descriptor,
        new java.lang.String[] { "MitmserverId", "CloudId", "Url", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
