// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

public interface MitmBindingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmBinding)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mitmserverId = 1;</code>
   */
  java.lang.String getMitmserverId();
  /**
   * <code>string mitmserverId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMitmserverIdBytes();

  /**
   * <code>string browserId = 2;</code>
   */
  java.lang.String getBrowserId();
  /**
   * <code>string browserId = 2;</code>
   */
  com.google.protobuf.ByteString
      getBrowserIdBytes();
}
