// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

public interface MitmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mitmserverId = 1;</code>
   */
  java.lang.String getMitmserverId();
  /**
   * <code>string mitmserverId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMitmserverIdBytes();

  /**
   * <code>string cloudId = 2;</code>
   */
  java.lang.String getCloudId();
  /**
   * <code>string cloudId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCloudIdBytes();

  /**
   * <code>string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>bytes content = 4;</code>
   */
  com.google.protobuf.ByteString getContent();
}
