// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

public interface MitmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mitm.MitmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  boolean hasMitmBinding();
  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmBinding getMitmBinding();
  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder getMitmBindingOrBuilder();

  /**
   * <code>.mitm.MitmRequest request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.mitm.MitmRequest request = 2;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmRequest getRequest();
  /**
   * <code>.mitm.MitmRequest request = 2;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader> 
      getHeadersList();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmHeader getHeaders(int index);
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  int getHeadersCount();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  java.util.List<? extends com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder> 
      getHeadersOrBuilderList();
  /**
   * <code>repeated .mitm.MitmHeader headers = 3;</code>
   */
  com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder getHeadersOrBuilder(
      int index);

  /**
   * <code>bytes content = 5;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int32 statusCode = 6;</code>
   */
  int getStatusCode();
}
