// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

/**
 * Protobuf type {@code mitm.MitmRequest}
 */
public  final class MitmRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmRequest)
    MitmRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmRequest.newBuilder() to construct.
  private MitmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmRequest() {
    url_ = "";
    method_ = "";
    headers_ = java.util.Collections.emptyList();
    content_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder subBuilder = null;
            if (mitmBinding_ != null) {
              subBuilder = mitmBinding_.toBuilder();
            }
            mitmBinding_ = input.readMessage(com.deep007.goniub.selenium.mitm.monitor.MitmBinding.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mitmBinding_);
              mitmBinding_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            method_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              headers_ = new java.util.ArrayList<com.deep007.goniub.selenium.mitm.monitor.MitmHeader>();
              mutable_bitField0_ |= 0x00000008;
            }
            headers_.add(
                input.readMessage(com.deep007.goniub.selenium.mitm.monitor.MitmHeader.parser(), extensionRegistry));
            break;
          }
          case 42: {

            content_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        headers_ = java.util.Collections.unmodifiableList(headers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.goniub.selenium.mitm.monitor.MitmRequest.class, com.deep007.goniub.selenium.mitm.monitor.MitmRequest.Builder.class);
  }

  private int bitField0_;
  public static final int MITMBINDING_FIELD_NUMBER = 1;
  private com.deep007.goniub.selenium.mitm.monitor.MitmBinding mitmBinding_;
  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  public boolean hasMitmBinding() {
    return mitmBinding_ != null;
  }
  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  public com.deep007.goniub.selenium.mitm.monitor.MitmBinding getMitmBinding() {
    return mitmBinding_ == null ? com.deep007.goniub.selenium.mitm.monitor.MitmBinding.getDefaultInstance() : mitmBinding_;
  }
  /**
   * <code>.mitm.MitmBinding mitmBinding = 1;</code>
   */
  public com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder getMitmBindingOrBuilder() {
    return getMitmBinding();
  }

  public static final int URL_FIELD_NUMBER = 2;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 2;</code>
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 3;
  private volatile java.lang.Object method_;
  /**
   * <code>string method = 3;</code>
   */
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADERS_FIELD_NUMBER = 4;
  private java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader> headers_;
  /**
   * <code>repeated .mitm.MitmHeader headers = 4;</code>
   */
  public java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader> getHeadersList() {
    return headers_;
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 4;</code>
   */
  public java.util.List<? extends com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder> 
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 4;</code>
   */
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 4;</code>
   */
  public com.deep007.goniub.selenium.mitm.monitor.MitmHeader getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <code>repeated .mitm.MitmHeader headers = 4;</code>
   */
  public com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString content_;
  /**
   * <code>bytes content = 5;</code>
   */
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mitmBinding_ != null) {
      output.writeMessage(1, getMitmBinding());
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
    }
    if (!getMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
    }
    for (int i = 0; i < headers_.size(); i++) {
      output.writeMessage(4, headers_.get(i));
    }
    if (!content_.isEmpty()) {
      output.writeBytes(5, content_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mitmBinding_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMitmBinding());
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
    }
    if (!getMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
    }
    for (int i = 0; i < headers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, headers_.get(i));
    }
    if (!content_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, content_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.goniub.selenium.mitm.monitor.MitmRequest)) {
      return super.equals(obj);
    }
    com.deep007.goniub.selenium.mitm.monitor.MitmRequest other = (com.deep007.goniub.selenium.mitm.monitor.MitmRequest) obj;

    boolean result = true;
    result = result && (hasMitmBinding() == other.hasMitmBinding());
    if (hasMitmBinding()) {
      result = result && getMitmBinding()
          .equals(other.getMitmBinding());
    }
    result = result && getUrl()
        .equals(other.getUrl());
    result = result && getMethod()
        .equals(other.getMethod());
    result = result && getHeadersList()
        .equals(other.getHeadersList());
    result = result && getContent()
        .equals(other.getContent());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMitmBinding()) {
      hash = (37 * hash) + MITMBINDING_FIELD_NUMBER;
      hash = (53 * hash) + getMitmBinding().hashCode();
    }
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    if (getHeadersCount() > 0) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeadersList().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.goniub.selenium.mitm.monitor.MitmRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmRequest)
      com.deep007.goniub.selenium.mitm.monitor.MitmRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.goniub.selenium.mitm.monitor.MitmRequest.class, com.deep007.goniub.selenium.mitm.monitor.MitmRequest.Builder.class);
    }

    // Construct using com.deep007.goniub.selenium.mitm.monitor.MitmRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeadersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (mitmBindingBuilder_ == null) {
        mitmBinding_ = null;
      } else {
        mitmBinding_ = null;
        mitmBindingBuilder_ = null;
      }
      url_ = "";

      method_ = "";

      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        headersBuilder_.clear();
      }
      content_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstanceForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmRequest.getDefaultInstance();
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest build() {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest buildPartial() {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest result = new com.deep007.goniub.selenium.mitm.monitor.MitmRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (mitmBindingBuilder_ == null) {
        result.mitmBinding_ = mitmBinding_;
      } else {
        result.mitmBinding_ = mitmBindingBuilder_.build();
      }
      result.url_ = url_;
      result.method_ = method_;
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.headers_ = headers_;
      } else {
        result.headers_ = headersBuilder_.build();
      }
      result.content_ = content_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.goniub.selenium.mitm.monitor.MitmRequest) {
        return mergeFrom((com.deep007.goniub.selenium.mitm.monitor.MitmRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.goniub.selenium.mitm.monitor.MitmRequest other) {
      if (other == com.deep007.goniub.selenium.mitm.monitor.MitmRequest.getDefaultInstance()) return this;
      if (other.hasMitmBinding()) {
        mergeMitmBinding(other.getMitmBinding());
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        onChanged();
      }
      if (headersBuilder_ == null) {
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
      } else {
        if (!other.headers_.isEmpty()) {
          if (headersBuilder_.isEmpty()) {
            headersBuilder_.dispose();
            headersBuilder_ = null;
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            headersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeadersFieldBuilder() : null;
          } else {
            headersBuilder_.addAllMessages(other.headers_);
          }
        }
      }
      if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
        setContent(other.getContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.goniub.selenium.mitm.monitor.MitmRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.deep007.goniub.selenium.mitm.monitor.MitmBinding mitmBinding_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.deep007.goniub.selenium.mitm.monitor.MitmBinding, com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder> mitmBindingBuilder_;
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public boolean hasMitmBinding() {
      return mitmBindingBuilder_ != null || mitmBinding_ != null;
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmBinding getMitmBinding() {
      if (mitmBindingBuilder_ == null) {
        return mitmBinding_ == null ? com.deep007.goniub.selenium.mitm.monitor.MitmBinding.getDefaultInstance() : mitmBinding_;
      } else {
        return mitmBindingBuilder_.getMessage();
      }
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public Builder setMitmBinding(com.deep007.goniub.selenium.mitm.monitor.MitmBinding value) {
      if (mitmBindingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mitmBinding_ = value;
        onChanged();
      } else {
        mitmBindingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public Builder setMitmBinding(
        com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder builderForValue) {
      if (mitmBindingBuilder_ == null) {
        mitmBinding_ = builderForValue.build();
        onChanged();
      } else {
        mitmBindingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public Builder mergeMitmBinding(com.deep007.goniub.selenium.mitm.monitor.MitmBinding value) {
      if (mitmBindingBuilder_ == null) {
        if (mitmBinding_ != null) {
          mitmBinding_ =
            com.deep007.goniub.selenium.mitm.monitor.MitmBinding.newBuilder(mitmBinding_).mergeFrom(value).buildPartial();
        } else {
          mitmBinding_ = value;
        }
        onChanged();
      } else {
        mitmBindingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public Builder clearMitmBinding() {
      if (mitmBindingBuilder_ == null) {
        mitmBinding_ = null;
        onChanged();
      } else {
        mitmBinding_ = null;
        mitmBindingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder getMitmBindingBuilder() {
      
      onChanged();
      return getMitmBindingFieldBuilder().getBuilder();
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder getMitmBindingOrBuilder() {
      if (mitmBindingBuilder_ != null) {
        return mitmBindingBuilder_.getMessageOrBuilder();
      } else {
        return mitmBinding_ == null ?
            com.deep007.goniub.selenium.mitm.monitor.MitmBinding.getDefaultInstance() : mitmBinding_;
      }
    }
    /**
     * <code>.mitm.MitmBinding mitmBinding = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.deep007.goniub.selenium.mitm.monitor.MitmBinding, com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder> 
        getMitmBindingFieldBuilder() {
      if (mitmBindingBuilder_ == null) {
        mitmBindingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.deep007.goniub.selenium.mitm.monitor.MitmBinding, com.deep007.goniub.selenium.mitm.monitor.MitmBinding.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmBindingOrBuilder>(
                getMitmBinding(),
                getParentForChildren(),
                isClean());
        mitmBinding_ = null;
      }
      return mitmBindingBuilder_;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 2;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 2;</code>
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 2;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 3;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 3;</code>
     */
    public Builder setMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 3;</code>
     */
    public Builder clearMethod() {
      
      method_ = getDefaultInstance().getMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string method = 3;</code>
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      method_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader> headers_ =
      java.util.Collections.emptyList();
    private void ensureHeadersIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        headers_ = new java.util.ArrayList<com.deep007.goniub.selenium.mitm.monitor.MitmHeader>(headers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.deep007.goniub.selenium.mitm.monitor.MitmHeader, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder> headersBuilder_;

    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader> getHeadersList() {
      if (headersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(headers_);
      } else {
        return headersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public int getHeadersCount() {
      if (headersBuilder_ == null) {
        return headers_.size();
      } else {
        return headersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmHeader getHeaders(int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);
      } else {
        return headersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder setHeaders(
        int index, com.deep007.goniub.selenium.mitm.monitor.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
      } else {
        headersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder setHeaders(
        int index, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.set(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder addHeaders(com.deep007.goniub.selenium.mitm.monitor.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
      } else {
        headersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder addHeaders(
        int index, com.deep007.goniub.selenium.mitm.monitor.MitmHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(index, value);
        onChanged();
      } else {
        headersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder addHeaders(
        com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder addHeaders(
        int index, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder addAllHeaders(
        java.lang.Iterable<? extends com.deep007.goniub.selenium.mitm.monitor.MitmHeader> values) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
      } else {
        headersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder clearHeaders() {
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        headersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public Builder removeHeaders(int index) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.remove(index);
        onChanged();
      } else {
        headersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder getHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder getHeadersOrBuilder(
        int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);  } else {
        return headersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public java.util.List<? extends com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder> 
         getHeadersOrBuilderList() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(headers_);
      }
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder addHeadersBuilder() {
      return getHeadersFieldBuilder().addBuilder(
          com.deep007.goniub.selenium.mitm.monitor.MitmHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder addHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().addBuilder(
          index, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mitm.MitmHeader headers = 4;</code>
     */
    public java.util.List<com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder> 
         getHeadersBuilderList() {
      return getHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.deep007.goniub.selenium.mitm.monitor.MitmHeader, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder> 
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.deep007.goniub.selenium.mitm.monitor.MitmHeader, com.deep007.goniub.selenium.mitm.monitor.MitmHeader.Builder, com.deep007.goniub.selenium.mitm.monitor.MitmHeaderOrBuilder>(
                headers_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes content = 5;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <code>bytes content = 5;</code>
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes content = 5;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmRequest)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmRequest)
  private static final com.deep007.goniub.selenium.mitm.monitor.MitmRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.goniub.selenium.mitm.monitor.MitmRequest();
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmRequest>
      PARSER = new com.google.protobuf.AbstractParser<MitmRequest>() {
    public MitmRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmRequest> getParserForType() {
    return PARSER;
  }

  public com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

