// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mitm_flow.proto

package com.deep007.goniub.selenium.mitm.monitor;

/**
 * Protobuf type {@code mitm.MitmRequest}
 */
public  final class MitmRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mitm.MitmRequest)
    MitmRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MitmRequest.newBuilder() to construct.
  private MitmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MitmRequest() {
    mitmserverId_ = "";
    cloudId_ = "";
    url_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MitmRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mitmserverId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cloudId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.deep007.goniub.selenium.mitm.monitor.MitmRequest.class, com.deep007.goniub.selenium.mitm.monitor.MitmRequest.Builder.class);
  }

  public static final int MITMSERVERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object mitmserverId_;
  /**
   * <code>string mitmserverId = 1;</code>
   */
  public java.lang.String getMitmserverId() {
    java.lang.Object ref = mitmserverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mitmserverId_ = s;
      return s;
    }
  }
  /**
   * <code>string mitmserverId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMitmserverIdBytes() {
    java.lang.Object ref = mitmserverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mitmserverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOUDID_FIELD_NUMBER = 2;
  private volatile java.lang.Object cloudId_;
  /**
   * <code>string cloudId = 2;</code>
   */
  public java.lang.String getCloudId() {
    java.lang.Object ref = cloudId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cloudId_ = s;
      return s;
    }
  }
  /**
   * <code>string cloudId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCloudIdBytes() {
    java.lang.Object ref = cloudId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cloudId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 3;</code>
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMitmserverIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mitmserverId_);
    }
    if (!getCloudIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cloudId_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMitmserverIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mitmserverId_);
    }
    if (!getCloudIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cloudId_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.deep007.goniub.selenium.mitm.monitor.MitmRequest)) {
      return super.equals(obj);
    }
    com.deep007.goniub.selenium.mitm.monitor.MitmRequest other = (com.deep007.goniub.selenium.mitm.monitor.MitmRequest) obj;

    boolean result = true;
    result = result && getMitmserverId()
        .equals(other.getMitmserverId());
    result = result && getCloudId()
        .equals(other.getCloudId());
    result = result && getUrl()
        .equals(other.getUrl());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MITMSERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getMitmserverId().hashCode();
    hash = (37 * hash) + CLOUDID_FIELD_NUMBER;
    hash = (53 * hash) + getCloudId().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.deep007.goniub.selenium.mitm.monitor.MitmRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mitm.MitmRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mitm.MitmRequest)
      com.deep007.goniub.selenium.mitm.monitor.MitmRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deep007.goniub.selenium.mitm.monitor.MitmRequest.class, com.deep007.goniub.selenium.mitm.monitor.MitmRequest.Builder.class);
    }

    // Construct using com.deep007.goniub.selenium.mitm.monitor.MitmRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mitmserverId_ = "";

      cloudId_ = "";

      url_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmFlowMonitorProto.internal_static_mitm_MitmRequest_descriptor;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstanceForType() {
      return com.deep007.goniub.selenium.mitm.monitor.MitmRequest.getDefaultInstance();
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest build() {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.deep007.goniub.selenium.mitm.monitor.MitmRequest buildPartial() {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest result = new com.deep007.goniub.selenium.mitm.monitor.MitmRequest(this);
      result.mitmserverId_ = mitmserverId_;
      result.cloudId_ = cloudId_;
      result.url_ = url_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.deep007.goniub.selenium.mitm.monitor.MitmRequest) {
        return mergeFrom((com.deep007.goniub.selenium.mitm.monitor.MitmRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.deep007.goniub.selenium.mitm.monitor.MitmRequest other) {
      if (other == com.deep007.goniub.selenium.mitm.monitor.MitmRequest.getDefaultInstance()) return this;
      if (!other.getMitmserverId().isEmpty()) {
        mitmserverId_ = other.mitmserverId_;
        onChanged();
      }
      if (!other.getCloudId().isEmpty()) {
        cloudId_ = other.cloudId_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.deep007.goniub.selenium.mitm.monitor.MitmRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.deep007.goniub.selenium.mitm.monitor.MitmRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mitmserverId_ = "";
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public java.lang.String getMitmserverId() {
      java.lang.Object ref = mitmserverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mitmserverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMitmserverIdBytes() {
      java.lang.Object ref = mitmserverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mitmserverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder setMitmserverId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mitmserverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder clearMitmserverId() {
      
      mitmserverId_ = getDefaultInstance().getMitmserverId();
      onChanged();
      return this;
    }
    /**
     * <code>string mitmserverId = 1;</code>
     */
    public Builder setMitmserverIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mitmserverId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cloudId_ = "";
    /**
     * <code>string cloudId = 2;</code>
     */
    public java.lang.String getCloudId() {
      java.lang.Object ref = cloudId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cloudId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cloudId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCloudIdBytes() {
      java.lang.Object ref = cloudId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cloudId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cloudId = 2;</code>
     */
    public Builder setCloudId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cloudId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cloudId = 2;</code>
     */
    public Builder clearCloudId() {
      
      cloudId_ = getDefaultInstance().getCloudId();
      onChanged();
      return this;
    }
    /**
     * <code>string cloudId = 2;</code>
     */
    public Builder setCloudIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cloudId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 3;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 3;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 3;</code>
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 3;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mitm.MitmRequest)
  }

  // @@protoc_insertion_point(class_scope:mitm.MitmRequest)
  private static final com.deep007.goniub.selenium.mitm.monitor.MitmRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.deep007.goniub.selenium.mitm.monitor.MitmRequest();
  }

  public static com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MitmRequest>
      PARSER = new com.google.protobuf.AbstractParser<MitmRequest>() {
    public MitmRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MitmRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MitmRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MitmRequest> getParserForType() {
    return PARSER;
  }

  public com.deep007.goniub.selenium.mitm.monitor.MitmRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

